# Generated by Django 3.2.9 on 2021-12-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='back',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='back',
            name='password',
            field=models.CharField(default='username@123', max_length=20),
        ),
    ]
