# Generated by Django 3.2.9 on 2021-12-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211213_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='back',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
