# Generated by Django 3.2.9 on 2021-12-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_back_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Back1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
